---
title: "TidyTemplate"
date: 2022-09-14
output: html_document
editor_options: 
  chunk_output_type: console
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(lubridate)
library(gganimate)

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2022-09-13")

```


# Readme

T
```{r Readme, eval = interactive()}

tt

```


# Glimpse Data



```{r}
bigfoot <- tt$bigfoot %>% mutate(year = year(date))
bigfoot %>% count(season)
bigfoot %>% ggplot(aes(x=year)) + geom_histogram()
bigfoot %>% filter(year > 1900) %>% ggplot(aes(x=year)) + geom_histogram()
```


map?

```{r}
bigfoot %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + borders("state")

p_small <- bigfoot %>% filter( state != "Alaska") %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + borders("state")


p_small <- bigfoot %>% filter( state != "Alaska",
                               longitude > -135) %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + borders("state")

#belwo for aaniamt


p_small + labs(title = 'Year: {current_frame}') + transition_time(year)

p_small + labs(title = 'Year: {current_frame}') +   transition_manual(year, cumulative = TRUE)



```





does day of the week effect sightings?

```{r}
bigfoot %>% mutate(day = wday(date, label = T))
bigfoot %>% mutate(day = wday(date, label = T)) %>% 
  count(day, sort=T)

bigfoot %>% mutate(day = wday(date, label = T)) %>%  filter(!is.na(day))  %>% 
  count(day, sort=T)  %>% ggplot(aes(day, n)) + geom_col()

bigfoot %>% mutate(day = wday(date, label = T)) %>%  filter(!is.na(day))  %>% 
  count(day, season, sort=T)  %>% ggplot(aes(day, n, fill=season)) + geom_col()
```


is there a trend over time?
link between popsize?


words

```{r}
library(tidytext)
bigfoot %>% unnest_tokens(word, observed) %>% count(word, sort=T)


word_list <- bigfoot %>% unnest_tokens(word, observed)  %>% anti_join(stop_words) %>% count(word, sort=T)

install.packages("devtools")

devtools::install_github("lchiffon/wordcloud2")



library(wordcloud2)
wordcloud2(data = word_list)

# # 
# install.packages("widyr")
# library(widyr)
# install.packages("ggraph")
# library(ggraph)
# 
# word_list %>% 
#   pairwise_cor(word, id)
# 

word_list %>% 
  inner_join(get_sentiments("bing"))


word_list %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(sentiment)



word_list %>% 
  inner_join(get_sentiments("bing")) 

# 
# word_list %>% 
#   inner_join(get_sentiments("bing")) %>% 
# pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>%   mutate(sentiment = positive - negative)


word_list  %>% 
 inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) 


sent_list <- word_list  %>% 
 inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE)


```



predict


```{r}
library(tidymodels)
set.seed(1234)

#note doesn't work with 3...
bigfoot_split <- bigfoot %>% filter(classification != "Class C") %>%  initial_split()
bigfoot_split

bigfoot_train  <-training(bigfoot_split)
bigfoot_test <-   testing(bigfoot_split)

bigfoot_train_fold <- bigfoot_train %>% vfold_cv(3)

recipe(classification ~ state, bigfoot_train) %>% 
  workflow(logistic_reg()) %>% 
  fit_resamples(bigfoot_train_fold) %>% 
  collect_metrics()

recipe(classification ~ state + year + season, bigfoot_train) %>% 
  workflow(logistic_reg()) %>% 
  fit_resamples(bigfoot_train_fold) %>% 
  collect_metrics()



recipe(classification ~ state + year + season, bigfoot_train) %>% 
  workflow(logistic_reg()) %>% 
  fit_resamples(bigfoot_train_fold) %>% 
  collect_metrics()

```



#https://cran.r-project.org/web/packages/usmap/vignettes/mapping.html


```{r}
install.packages("usmap")
library(usmap)

bigfoot %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + coord_map()
bigfoot %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + coord_map() + theme_void()
bigfoot %>% ggplot(aes(x=longitude, y= latitude)) + geom_point() + coord_map() + theme_void() + borders("state")

bigfoot %>% ggplot(aes(x=longitude, y= latitude, color=season)) + geom_point() + coord_map() + theme_void() + borders("state")

bigfoot %>% plot_usmap(regions = "states")  %>% ggplot(aes(x=longitude, y= latitude)) + geom_point()

bigfoot %>% plot_usmap(data = statepop, values = "pop_2015")  %>% ggplot(aes(x=longitude, y= latitude)) + geom_point()

transformed_bifoot  <- usmap_transform(bigfoot)



transformed_bifoot  <- usmap_transform(d1)

plot_usmap() + 
  geom_point(data = bigfoot, 
             aes(x = longitude, y = latitude), 
             color = "red",
             size = 3)


```


```{r}
library(maps)
library(mapdata)
usa <- map_data('usa')

ggplot(data=usa, aes(x=long, y=lat, group=group)) + geom_polygon(fill='lightblue')  + 
  geom_point(data = bigfoot, aes(x=longitude, y= latitude, color=season))

MainStates <- map_data("state")

ggplot() + 
  geom_polygon( data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )

p <-ggplot() + 
  geom_polygon( data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )


p + geom_point(data=bigfoot, aes(x=longitude, y= latitude, color=season)) 
```


```{r}
bigfoot %>% count(state, sort=T)
bigfoot %>% mutate(state = fct_lump(state, 20))  %>% count(state, sort=T)
bigfoot %>% mutate(state = fct_lump(state, 20))  %>% count(state, sort=T)
```

is there a trend over time?
link between popsize?


```{r}



p <-ggplot() + 
  geom_polygon( data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )


p1 <- p + geom_point(data=bigfoot, aes(x=longitude, y= latitude, color=season))


# install.packages("gganimate")

library(gganimate)
# install.packages("gifski")

library(lubridate)


 p + geom_point(data=bigfoot, aes(x=longitude, y= latitude, color=season)) +  labs(title = 'Year: {frame_time}') +
  transition_time(year)

 
 
p3 <-  p + geom_point(data=bigfoot, aes(x=longitude, y= latitude, color=season)) +  labs(title = 'Year: {frame_time}') +
  transition_time(year) 
 
 

p + geom_point(data=bigfoot, aes(x=longitude, y= latitude, color=season)) + coord_map() +   labs(title = 'Year: {round(frame_time,2)}') + transition_time(year) 


#remove alaska? 
#show weird ones





```


Todo

- tidytext stuff with a wordclurs and then a pairwise corr and m ayeb a network fraph 
